"""create initial MeetingAI schema

Revision ID: a2be71a104a2
Revises: 
Create Date: 2026-09-23 22:05:55.204335

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a2be71a104a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=191), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_table('meetings',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meeting_date', sa.DateTime(), nullable=True),
    sa.Column('language', sa.String(length=10), server_default=sa.text("'vi'"), nullable=False),
    sa.Column('status', mysql.ENUM('DRAFT', 'UPLOADED', 'PREPROCESSING', 'TRANSCRIBING', 'DIARIZING', 'ANALYZING', 'COMPLETED', 'FAILED'), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.Column('review_status', mysql.ENUM('DRAFT', 'CONFIRMED'), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('stored_filename', sa.String(length=255), nullable=True),
    sa.Column('audio_path', sa.String(length=500), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size_bytes', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('duration_seconds', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('failed_step', sa.String(length=64), nullable=True),
    sa.Column('audio_deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.create_index('idx_meetings_error_code', ['error_code'], unique=False)
        batch_op.create_index('idx_meetings_review_status', ['review_status'], unique=False)
        batch_op.create_index('idx_meetings_title', ['title'], unique=False)
        batch_op.create_index('idx_meetings_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('idx_meetings_user_date', ['user_id', 'meeting_date'], unique=False)
        batch_op.create_index('idx_meetings_user_status', ['user_id', 'status'], unique=False)

    op.create_table('ai_runs',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('meeting_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('run_type', mysql.ENUM('FULL', 'SUMMARY', 'DECISIONS', 'ACTION_ITEMS', 'RISKS', 'OPEN_QUESTIONS'), server_default=sa.text("'FULL'"), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('model_version', sa.String(length=120), nullable=False),
    sa.Column('dataset_version', sa.String(length=120), nullable=True),
    sa.Column('prompt_version', sa.String(length=120), nullable=True),
    sa.Column('schema_version', sa.String(length=50), nullable=True),
    sa.Column('status', mysql.ENUM('RUNNING', 'COMPLETED', 'FAILED'), server_default=sa.text("'RUNNING'"), nullable=False),
    sa.Column('processing_ms', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('input_chars', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('input_tokens', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('is_accepted', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_runs', schema=None) as batch_op:
        batch_op.create_index('idx_airuns_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_airuns_meeting_created', ['meeting_id', 'created_at'], unique=False)
        batch_op.create_index('idx_airuns_model_name', ['model_name'], unique=False)
        batch_op.create_index('idx_airuns_model_version', ['model_version'], unique=False)
        batch_op.create_index('idx_airuns_run_type', ['run_type'], unique=False)
        batch_op.create_index('idx_airuns_status', ['status'], unique=False)

    op.create_table('processing_jobs',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('meeting_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('job_type', mysql.ENUM('FULL', 'TRANSCRIBE', 'DIARIZE', 'ANALYZE', 'REGENERATE'), server_default=sa.text("'FULL'"), nullable=False),
    sa.Column('status', mysql.ENUM('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED'), server_default=sa.text("'QUEUED'"), nullable=False),
    sa.Column('progress_percent', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=False),
    sa.Column('current_step', sa.String(length=64), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('asr_model_name', sa.String(length=120), nullable=True),
    sa.Column('asr_model_version', sa.String(length=120), nullable=True),
    sa.Column('checkpoint_stage', sa.String(length=64), nullable=True),
    sa.Column('checkpoint_data', mysql.JSON(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.create_index('idx_jobs_job_type', ['job_type'], unique=False)
        batch_op.create_index('idx_jobs_meeting_created', ['meeting_id', 'created_at'], unique=False)
        batch_op.create_index('idx_jobs_status', ['status'], unique=False)

    op.create_table('speakers',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('meeting_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('speaker_label', sa.String(length=50), nullable=False),
    sa.Column('speaker_name', sa.String(length=120), nullable=True),
    sa.Column('is_user_verified', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'speaker_label', name='uq_speakers_meeting_label')
    )
    op.create_table('summaries',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('meeting_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('ai_run_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('content', sa.Text().with_variant(sa.Text(length=4294967295), 'mysql'), nullable=False),
    sa.Column('is_user_edited', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['ai_run_id'], ['ai_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.create_index('idx_summaries_meeting', ['meeting_id', 'created_at'], unique=False)

    op.create_table('transcript_segments',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('meeting_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('speaker_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('segment_index', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('start_ms', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('end_ms', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('edited_text', sa.Text(), nullable=True),
    sa.Column('asr_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('is_user_edited', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'segment_index', name='uq_segments_meeting_idx')
    )
    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.create_index('idx_segments_is_user_edited', ['is_user_edited'], unique=False)
        batch_op.create_index('idx_segments_meeting_time', ['meeting_id', 'start_ms'], unique=False)
        batch_op.create_index('idx_segments_speaker_id', ['speaker_id'], unique=False)

    op.create_table('action_items',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('meeting_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('ai_run_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('deadline_raw', sa.String(length=255), nullable=True),
    sa.Column('deadline_normalized', sa.Date(), nullable=True),
    sa.Column('task_status', mysql.ENUM('TODO', 'IN_PROGRESS', 'DONE', 'CANCELLED'), server_default=sa.text("'TODO'"), nullable=False),
    sa.Column('confidence_level', mysql.ENUM('HIGH', 'MEDIUM', 'LOW'), nullable=True),
    sa.Column('evidence_segment_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('is_user_edited', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['ai_run_id'], ['ai_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evidence_segment_id'], ['transcript_segments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.create_index('idx_tasks_confidence', ['confidence_level'], unique=False)
        batch_op.create_index('idx_tasks_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_tasks_deadline_status', ['deadline_normalized', 'task_status'], unique=False)
        batch_op.create_index('idx_tasks_meeting_status', ['meeting_id', 'task_status'], unique=False)

    op.create_table('decisions',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('meeting_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('ai_run_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('decision_status', mysql.ENUM('CONFIRMED', 'TENTATIVE', 'REJECTED', 'SUPERSEDED'), server_default=sa.text("'CONFIRMED'"), nullable=False),
    sa.Column('confidence_level', mysql.ENUM('HIGH', 'MEDIUM', 'LOW'), nullable=True),
    sa.Column('evidence_segment_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('is_user_edited', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['ai_run_id'], ['ai_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evidence_segment_id'], ['transcript_segments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index('idx_decisions_confidence', ['confidence_level'], unique=False)
        batch_op.create_index('idx_decisions_status', ['decision_status'], unique=False)

    op.create_table('key_points',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('meeting_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('ai_run_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sort_order', mysql.SMALLINT(unsigned=True), server_default=sa.text('0'), nullable=False),
    sa.Column('evidence_segment_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('is_user_edited', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['ai_run_id'], ['ai_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evidence_segment_id'], ['transcript_segments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('action_item_owners',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('action_item_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('speaker_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('owner_name', sa.String(length=120), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['action_item_id'], ['action_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_item_owners', schema=None) as batch_op:
        batch_op.create_index('idx_owner_name', ['owner_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_item_owners', schema=None) as batch_op:
        batch_op.drop_index('idx_owner_name')

    op.drop_table('action_item_owners')
    op.drop_table('key_points')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index('idx_decisions_status')
        batch_op.drop_index('idx_decisions_confidence')

    op.drop_table('decisions')
    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.drop_index('idx_tasks_meeting_status')
        batch_op.drop_index('idx_tasks_deadline_status')
        batch_op.drop_index('idx_tasks_created_at')
        batch_op.drop_index('idx_tasks_confidence')

    op.drop_table('action_items')
    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.drop_index('idx_segments_speaker_id')
        batch_op.drop_index('idx_segments_meeting_time')
        batch_op.drop_index('idx_segments_is_user_edited')

    op.drop_table('transcript_segments')
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.drop_index('idx_summaries_meeting')

    op.drop_table('summaries')
    op.drop_table('speakers')
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.drop_index('idx_jobs_status')
        batch_op.drop_index('idx_jobs_meeting_created')
        batch_op.drop_index('idx_jobs_job_type')

    op.drop_table('processing_jobs')
    with op.batch_alter_table('ai_runs', schema=None) as batch_op:
        batch_op.drop_index('idx_airuns_status')
        batch_op.drop_index('idx_airuns_run_type')
        batch_op.drop_index('idx_airuns_model_version')
        batch_op.drop_index('idx_airuns_model_name')
        batch_op.drop_index('idx_airuns_meeting_created')
        batch_op.drop_index('idx_airuns_created_at')

    op.drop_table('ai_runs')
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_index('idx_meetings_user_status')
        batch_op.drop_index('idx_meetings_user_date')
        batch_op.drop_index('idx_meetings_user_created')
        batch_op.drop_index('idx_meetings_title')
        batch_op.drop_index('idx_meetings_review_status')
        batch_op.drop_index('idx_meetings_error_code')

    op.drop_table('meetings')
    op.drop_table('users')
    # ### end Alembic commands ###
